---
ingress-nginx:
  controller:
    registry: k8s.gcr.io
    image: ingress-nginx/controller
    tag: "v1.2.0"
    digest: sha256:d8196e3bc1e72547c5dec66d6556c0ff92a23f6d0919b206be170bc90d5f9185
    service:
      type: "LoadBalancer"
      loadBalancerIP: "34.107.31.210"
