---
name: gcfr-ingress
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - components/ingress/**
  pull_request:
    branches:
      - main
    paths:
      - components/ingress/**

jobs:
  gcfr-ingress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - id: gcloud auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCFR_GOOGLE_CREDENTIALS }}
      
      - name: connect to cluster
        run: gcloud container clusters get-credentials gcfr --region europe-west3 --project gcfr-352018
        env:
            GOOGLE_CREDENTIALS: ${{ secrets.GCFR_GOOGLE_CREDENTIALS }}
      
      - name: namespace apply
        run: kubectl apply -R -f namespace
        env:
            GOOGLE_CREDENTIALS: ${{ secrets.GCFR_GOOGLE_CREDENTIALS }}

      - name: helm install
        run: helm upgrade --install  -f ./components/ingress/values.yaml ingress ./components/ingress
        env:
            GOOGLE_CREDENTIALS: ${{ secrets.GCFR_GOOGLE_CREDENTIALS }}
