---
name: state-create
on:
  workflow_dispatch:
permissions:
  pull-requests: write
  contents: read

jobs:
  gcfr:
    uses: g14com0/kube-cluster/.github/workflows/tf-template.yml@main
    with:
      environment: gcfr
      path: gcs-tfstate
    secrets:
      GOOGLE_CREDENTIALS: ${{ secrets.GCFR_GOOGLE_CREDENTIALS }}
